services:
  redis:
    image: redis/redis-stack-server:latest
    command:
      - sh
      - -c
      - |
        redis-server /redis.conf --requirepass "$$(cat /run/secrets/REDIS_PASSWORD)"
    ports:
      - "6379:6379"
    networks:
      - redis_network
    secrets:
      - REDIS_PASSWORD
      - ca.pem
      - redis_server_cert.pem
      - redis_server_key.pem
      - fastapi_client_cert.pem
      - fastapi_client_key.pem
    environment:
      - REDIS_PASSWORD=/run/secrets/REDIS_PASSWORD
    volumes:
      - ./configurations/redis/redis.conf:/redis.conf:ro
      - ./volumes/redis_storage:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'redis-cli --tls --cacert /run/secrets/ca.pem --cert /run/secrets/fastapi_client_cert.pem --key /run/secrets/fastapi_client_key.pem  -a "$$(cat /run/secrets/REDIS_PASSWORD)" ping | grep PONG',
        ]
      interval: 5s
      timeout: 5s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          [
            node.role == manager,
          ]
      restart_policy:
        condition: on-failure

volumes:
  redis_storage:
    name: redis_storage_volume

secrets:
  REDIS_PASSWORD:
    external: true
  ca.pem:
    external: true
  redis_server_cert.pem:
    external: true
  redis_server_key.pem:
    external: true
  fastapi_client_cert.pem:
    external: true
  fastapi_client_key.pem:
    external: true

networks:
  redis_network:
    attachable: true
    external: true
    name: redis_default
