services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - ca.pem
      - pg_server_cert.pem
      - pg_server_key.pem
    environment:
      - POSTGRES_DB=/run/secrets/POSTGRES_DB
      - POSTGRES_USER=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD=/run/secrets/POSTGRES_PASSWORD
    volumes:
      - ./configurations/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./configurations/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./volumes/postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_storage:
    name: postgres_storage_volume

secrets:
  POSTGRES_DB:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  ca.pem:
    external: true
  pg_server_cert.pem:
    external: true
  pg_server_key.pem:
    external: true