"""initial migration

Revision ID: 1c16e07c92f8
Revises: 
Create Date: 2025-09-02 19:07:56.504777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c16e07c92f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_table',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chat_table',
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_table',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_table',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.String(length=255), nullable=True),
    sa.Column('banner_color', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('admin', 'regular', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='user_status'), nullable=False),
    sa.Column('follow_policy', sa.Enum('auto_accept', 'manual_approval', name='follow_policy'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_index(op.f('ix_user_table_name'), 'user_table', ['name'], unique=True)
    op.create_index(op.f('ix_user_table_username'), 'user_table', ['username'], unique=True)
    op.create_table('vocabulary_table',
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('block_table',
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_table',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('video_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participant_table',
    sa.Column('background_url', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', 'id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uq_user_chat')
    )
    op.create_table('feed_table',
    sa.Column('body', sa.String(length=200), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('video_aspect_ratio', sa.Float(precision=4), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_aspect_ratio', sa.Float(precision=4), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('feed_visibility', sa.Enum('public', 'followers', 'private', name='feed_visibility'), nullable=False),
    sa.Column('comment_policy', sa.Enum('everyone', 'followers', name='comment_policy'), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['feed_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['feed_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_table',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('follow_status', sa.Enum('pending', 'accepted', 'declined', name='follow_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follower_following')
    )
    op.create_table('group_table',
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('background_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('group_type', sa.Enum('public', 'private', name='group_type'), nullable=False),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_group_name')
    )
    op.create_table('meaning_table',
    sa.Column('part_of_speech', sa.String(length=50), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_table',
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=36)), nullable=True),
    sa.Column('collaborators', sa.ARRAY(sa.String(length=36)), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String(length=255), dimensions=12), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('(title IS NOT NULL AND body IS NULL) OR (body IS NULL AND title IS NOT NULL)', name='one_field_not_null_constraint'),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phonetic_table',
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_table',
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_vocabulary_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocabulary_id', name='_user_vocab_uc')
    )
    op.create_table('checklist_table',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text', 'is_done', 'note_id', name='uq_note_checklist')
    )
    op.create_table('definition_table',
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('meaning_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meaning_id'], ['meaning_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('engagement_type', sa.Enum('feeds', 'reposts', 'quotes', 'likes', 'views', 'bookmarks', name='engagement_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_tag_link_table',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'tag_id', 'id')
    )
    op.create_table('group_message_table',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('video_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_participant_table',
    sa.Column('member_type', sa.Enum('owner', 'administrator', 'moderator', 'regular', name='member_type'), nullable=False),
    sa.Column('background_url', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', 'id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_table('report_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('report_reason', sa.Enum('copyright_infringement', 'spam', 'nudity_or_sexual_content', 'misinformation', 'harassment_or_bullying', 'hate_speech', 'violence_or_threats', 'self_harm_or_suicide', 'impersonation', 'other', name='report_reason'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feed_id', 'report_reason', name='uq_feed_report')
    )
    op.create_table('sentence_word_association',
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence_table.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_table.id'], ),
    sa.PrimaryKeyConstraint('sentence_id', 'word_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_word_association')
    op.drop_table('report_table')
    op.drop_table('group_participant_table')
    op.drop_table('group_message_table')
    op.drop_table('feed_tag_link_table')
    op.drop_table('engagement_table')
    op.drop_table('definition_table')
    op.drop_table('checklist_table')
    op.drop_table('user_vocabulary_table')
    op.drop_table('sentence_table')
    op.drop_table('phonetic_table')
    op.drop_table('note_table')
    op.drop_table('meaning_table')
    op.drop_table('group_table')
    op.drop_table('follow_table')
    op.drop_table('feed_table')
    op.drop_table('chat_participant_table')
    op.drop_table('chat_message_table')
    op.drop_table('block_table')
    op.drop_table('vocabulary_table')
    op.drop_index(op.f('ix_user_table_username'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_name'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_table('tag_table')
    op.drop_table('chat_table')
    op.drop_table('category_table')
    # ### end Alembic commands ###
