"""some fixes model

Revision ID: 49ad1dc30bf7
Revises: e72c1bf6b0bf
Create Date: 2025-07-27 16:22:51.387543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ad1dc30bf7'
down_revision: Union[str, Sequence[str], None] = 'e72c1bf6b0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
