"""no_cascade_for_sentence words

Revision ID: 6f740d75fb6a
Revises: 243c3fb6c88f
Create Date: 2025-08-02 15:50:02.743600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f740d75fb6a'
down_revision: Union[str, Sequence[str], None] = '243c3fb6c88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
