"""fixed engagement model

Revision ID: 72f984320670
Revises: e9dc52f39a32
Create Date: 2025-08-08 15:09:29.727362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f984320670'
down_revision: Union[str, Sequence[str], None] = 'e9dc52f39a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_feed_engagement'), 'engagement_table', type_='unique')
    op.alter_column('feed_table', 'video_aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.alter_column('feed_table', 'image_aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_table', 'image_aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('feed_table', 'video_aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_feed_engagement'), 'engagement_table', ['user_id', 'feed_id', 'engagement_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
