"""added vocabulary model

Revision ID: e72c1bf6b0bf
Revises: b3115a703772
Create Date: 2025-07-27 15:20:54.616033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72c1bf6b0bf'
down_revision: Union[str, Sequence[str], None] = 'b3115a703772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_table',
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('transcription', sa.String(length=255), nullable=True),
    sa.Column('audio_pronunciation_url', sa.String(length=255), nullable=False),
    sa.Column('tab_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tab_id'], ['tab_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_collaborator_link_table',
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vocabulary_id', 'user_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_collaborator_link_table')
    op.drop_table('vocabulary_table')
    # ### end Alembic commands ###
