"""added image and video aspect ratio

Revision ID: e9dc52f39a32
Revises: bd36ff974727
Create Date: 2025-08-07 14:24:33.396569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9dc52f39a32'
down_revision: Union[str, Sequence[str], None] = 'bd36ff974727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_table', sa.Column('video_aspect_ratio', sa.Float(precision=4), nullable=True))
    op.add_column('feed_table', sa.Column('image_aspect_ratio', sa.Float(precision=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_table', 'image_aspect_ratio')
    op.drop_column('feed_table', 'video_aspect_ratio')
    # ### end Alembic commands ###
